### ISSUE TITLE
Smoothing for average color

### ISSUE THREAD

**Issue by abrenoch** [abrenoch/hyperion-android-grabber#109]
When using the average color grabber option, the calculated color changes can be a but abrupt. We could look into implementing a sort of smoothing for more dramatic color changes. Maybe something like a maximum step size when transitioning to the next color... I dunno. Seems like maybe this could be handled in the hyperion server settings but having to change them when changing the grabber type kind of stinks.

Just a thought, if anyone would like to take a stab at it!

**Comment by ninovanhooff** [comment]
I'll see what my experience is. Ive got quite a bit of smoothing over time in my config. Must admit I haven't tried the average color so far.

**Comment by Paulchen-Panther** [comment]
Hope this is helpfull: https://github.com/Bren730/android-ambilight/blob/master/app/src/main/java/nl/brendanspijkerman/android/ambilightscreencapture/ScreenCaptureFragment.java#L640

**Comment by ninovanhooff** [comment]
Implemented in v0.5
