### ISSUE TITLE
Doesn't work on most videos played

### ISSUE THREAD

**Issue by pmishev** [abrenoch/hyperion-android-grabber#117]
I'm running this on a Sony XF80 with android tv. It works while I'm in the home screen, browsing menus, etc.
In some apps, it works while browsing their interface too (Google video, Amazon video for example).
In other apps, it doesn't work even in their menus (BBC iPlayer fro example)
And for pretty much all apps I tried, The lights don't work for the video that is playing.
Same thing about YouView player for watching TV.
The only exception I found to work was Plex.

**Comment by Joeboyc2** [comment]
I have the same issue and I think it's a restriction of the Sony TV itself, I think it is DRM thing, but if there is a way round this I'd be happy to test

**Comment by abrenoch** [comment]
I think @Joeboyc2  is right. I have only done some light research into this but it appears it may be a hardware DRM thing. If nearly all video behaves the same, then I would wager it is something along those lines.

I've got a lot of feedback about the sony smart tvs and unfortunately this is a common theme... If anybody has any ideas that we could try out other than using the `MediaProjection` API I would love to hear them.

**Comment by Joeboyc2** [comment]
I've discovered recently that the lights actually work in the youtube app on android tv when the video is not a HD quality.

Is it something to do with the quality level of the screen?

**Comment by ivandompe** [comment]
Hi, I'm running this grabber (very good project) on a Minix X8-H plus with Lollipop 5.1. The hyperion master is on a PI3. The proto are well sent when I play video from KODI 17.6. Sounds good. Then on the  main screen on the lollipop os, when I navigate, the image is still transmitted to the master. It is also the case when I run Netflix, 'till I navigate on the app ambilight is working, but As soon as I play a Netlfix video, the grabber stop to work. I didn't try others video player.

**Comment by ivandompe** [comment]
Hope that this DRM issue could be solved soon... Thanks for the great job !

**Comment by ninovanhooff** [comment]
Please see https://github.com/abrenoch/hyperion-android-grabber/issues/12

For the main discussion on drm-protected content. (verdict at this moment: won't fix)

**Comment by fallenwitcher** [comment]
Its a player problem. Youtube, Netflix, Prime won't work. Kodi, VLC, or Mx Player works very well but unfortunately even emby won't work..
