### ISSUE TITLE
Intent to toggle screengrabber

### ISSUE THREAD

**Issue by whatdaybob** [abrenoch/hyperion-android-grabber#129]
Hi, I am having trouble using the new toggleactivity on Nvidia Shield, I have tried every possible combination of adb command to try and turn on and off the screengrabber except the correct way, I was hoping to integrate this into homeassistant. Can you please point me in the right direction to control the app via ADB commands as I cant read code well enough to figure this out.

**Comment by abrenoch** [comment]
Hey there @whatdaybob 

I believe the adb command would be:
`adb shell am start com.abrenoch.hyperiongrabber.tv/com.abrenoch.hyperiongrabber.common.ToggleActivity`

Just let me know if that doesn't work and we'll figure it out!

**Comment by whatdaybob** [comment]
Thanks, I will give it a go this weekend. Good suggestion on the remote power, I will consider that as an alternative, ideally I would like the ambilight to be on all times but to change to grabber mode when I have my android tv as the active input. This should hopefully accomplish that.

**Comment by abrenoch** [comment]
Closing out this issue, if there is still a problem just re-open
