### ISSUE TITLE
Testing Program Full

### ISSUE THREAD

**Issue by ShadowXVII** [abrenoch/hyperion-android-grabber#136]
Seems the testing program is full :(

> Thanks for your interest in becoming a tester for the Hyperion Android Grabber app.
> 
> However, at this time, Hyperion Android Grabber app's testing programme has reached the maximum number of testers that can participate in it and isn't accepting any more testers.

https://play.google.com/apps/testing/com.abrenoch.hyperiongrabber

**Comment by abrenoch** [comment]
I bumped up the max number of beta testers (the alpha channel can only have 100 it appears) - although they are the same right now. However, I'll be pushing out a full release by the end of this coming weekend!

**Comment by ShadowXVII** [comment]
Great thanks. Yeah looks open now 👍
