### ISSUE TITLE
Google Flatbuffers Support

### ISSUE THREAD

**Issue by drewrox2009** [abrenoch/hyperion-android-grabber#139]
my lights have been out of commission for a little while, i just spun up hyperion.ng and it looks like it doesn't have support for protobuffer input any longer.  Is there an easy way to implement support for the new flatbuffers protocol in this app. 

Or is there a way to get hyperion.ng to pick up the protobuffer input that i am missing?

Shot in the dark but i appreciate you developing this software

**Comment by Joeboyc2** [comment]
Hey @drewrox2009 protobuffer support is being readded to .ng source soon, there is an outstanding pull request that just needs approval https://github.com/hyperion-project/hyperion.ng/pull/539

There is a compiled version in the comments if you wanted to give it a go before it gets merged in to the base build

**Comment by drewrox2009** [comment]
Awesome! I am glad to see this hopefully I can get my lights running again soon!

**Comment by Paulchen-Panther** [comment]
The support of Flatbuffer would not be bad. Permanently the Protobuffer should not remain in the ng version. The performance of flatbuffer in the network is much better

**Comment by abrenoch** [comment]
This is probably a good idea if protobufs aren't going to be supported in the ng version anymore!

**Comment by flexage** [comment]
+1 would love to get ng support for this

**Comment by UniCizin** [comment]
Protobuf is back in .ng 
I use it with the Android grabber

**Comment by drewrox2009** [comment]
Just spun up the latest .ng. Got it working, But looks like even running emby i end up with a black screen sent to hyperion. Good old fire tv limitations. But anywho looks like this project isn't currently being developed. And this issue is now a non issue so it can be closed.
