### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FaserF** [abrenoch/hyperion-android-grabber#140]
Hi,

I am using a Hyperion Server on a raspberrypi 1B with some WS2812B Stripes.
I can control the stripes perfectly using Hyperion (I get the rainbow start animation) and using HomeAssistant (which can tell hyperion which scene or color to use.

But unfortunatly the Hyperion Android Screen Grabber for Android TV does nothing. It detects the Hyperion server fine, but once I enable it, the leds wont change at all.

Any help?

**Comment by Joeboyc2** [comment]
What version of hyperion are you using? NG?

Also what content are you trying to send to the lights? Where are you
running the grabber? On an android phone?

**Comment by FaserF** [comment]
I am so sorry, its working now, was my fault. My hyperion config had a mistake.
