### ISSUE TITLE
Sony TV Support

### ISSUE THREAD

**Issue by bverc** [abrenoch/hyperion-android-grabber#142]
Is there a minimum android version for Android TV?

I can install on all my devices except my Sony TV running Android 7. I checked the manifest, but nothing stood out

**Comment by abrenoch** [comment]
Hey @bverc 

Are you trying to sideload the APK to install from the playstore?

**Comment by bverc** [comment]
Sorry, forgot to specify. I am trying to install from the Play Store. Simply says, it is not compatible with this device, but all my other devices appear fine.

Could be geographic limitation or some other reason.

**Comment by abrenoch** [comment]
Well, for the time being at least, we have decided to limit the playstore TV listing to only devices that we know the app works on (to avoid being hammered with bad reviews for the many devices it does not work on).

Are you familiar with side-loading an apk? You could download the latest release from the releases section here and install it that way. If you are able to confirm some basic functionality I would be open to  whitelisting your device on the playstore.

Let me know if you need any help!

**Comment by bverc** [comment]
Sure will give it a go once I get my hyperion server up and running. Cheers.

**Comment by chiefymuc** [comment]
I can confirm this works on my Sony KD-49XF9005 TV on the latest android version. Could you please whitelist this? Thanks!

**Comment by ShadowXVII** [comment]
This installs and works on my KD55X9000F.

**Comment by drJeckyll** [comment]
Still don't have led hardware, but output to a file from Hyperion seems to works fine with my  Sony 49XE8005 and Android 8 oreo firmware 6.6555

**Comment by panec** [comment]
@ShadowXVII After installing it on TV do you have access to all video streams that are going thru tv, like stream from play station or only the apps from the android will allow to capture stream - like YT?

**Comment by ShadowXVII** [comment]
> @ShadowXVII After installing it on TV do you have access to all video streams that are going thru tv, like stream from play station or only the apps from the android will allow to capture stream - like YT?

No, unfortunately as discussed in #12 protected sources aren't visible. Other apps are fine. External inputs do not work.

**Comment by rysuq** [comment]
@ShadowXVII  I have Sony KD-55XD7005  on android  8.0 and before I  buy some items to my hyperion I want to know that will be work on my TV (on the other hand I can buy android box but I want to avoid  this buy). Can you record some video and show how it works ? I mean your input lag.

**Comment by ShadowXVII** [comment]
> @ShadowXVII  I have Sony KD-55XD7005  on android  8.0 and before I  buy some items to my hyperion I want to know that will be work on my TV (on the other hand I can buy android box but I want to avoid  this buy). Can you record some video and show how it works ? I mean your input lag.

The input lag itself is fine/not noticeable. It's the protected sources that really affect it most. 

I get better results from an inline HDMI capture. So I use a Chromecast despite having Android TV.

**Comment by bpavlov** [comment]
Hello, great job guys. It works on KD-43XD8005. Just wonder what is the difference between copy the .apk file to usb and install it from there and adb install .apk?

Also just a suggestion -> default value for priority is 50. It should be between 100 and 199.

**Comment by osswaldo** [comment]
I checked it on a Sony 55XF8096 and it worked fine (priority 100).
