### ISSUE TITLE
dose not work with Youtube app on my tv and 4K content  

### ISSUE THREAD

**Issue by DrCard** [abrenoch/hyperion-android-grabber#143]
the app works fine with most videos 720p and 1080p

the only issues I found is with youtube app the the Grabber is not sending any signals to the hyperion server 

the same issue is happening when playing 4k content on the TV  (also when playing 4k with kodi)

**Comment by DrCard** [comment]
can any one confirm that 4k videos and youtube app that the lights are working 

i found out  that when i use chromecast and cast a 1080p or a 720p videos the lights work but on 4K the light dont work 

also when i run any videos from the youtube app directly, the lights dont work

**Comment by DrCard** [comment]
No answers Guys ?

**Comment by Paulchen-Panther** [comment]
> No answers Guys ?
Du hast noch nicht mal geschrieben welche TV Marke du hast und erwartest eine Antwort?
Ist das dein ernst?

**Comment by DrCard** [comment]
Sorry 
i have a Sony 65x7500f

Thank you

**Comment by ninovanhooff** [comment]
Yeah we've seen a lot of issues with Sony tv's

**Comment by DrCard** [comment]
every thing else is full working i have been using it now for 3 months but with no 4K

if a chromcast to youtube the light work but if i go directly to the app the light work on the menu 

once the video is running the lights stop 
will there be any updates or any beta ver i can test ?

regards and thanks for the amazing work

**Comment by Joeboyc2** [comment]
I dont think this will work anytime soon, it seems to be a drm issue with
the hardware decoding the TV is doing to process the stream

**Comment by scotie** [comment]
I can confirm YouTube isn't working for my. Haven't tried the 4k content.

Using Mi Box S

**Comment by scotie** [comment]
I can confirm YouTube isn't working for my. Haven't tried the 4k content.

Using Mi Box S

**Comment by FaserF** [comment]
The official YouTube App is DRM protected, that's why it won't work.
Just use "Smart YouTube TV" instead, I am using it since months with Hyperion Grabber and it works great, even with 4K
