### ISSUE TITLE
black bars issue

### ISSUE THREAD

**Issue by DrCard** [abrenoch/hyperion-android-grabber#144]
if your movies have black bars the top and bottom lights are switched off as it is black 

with the intel hyperion Ambilight 1.0.2 it takes the black bars off and sends it to the Hyperion demand 

hope you can add this option

**Comment by abrenoch** [comment]
Have you tried configuring your hyperion server to remove the black bars? This is doable within the app, however we decided to encourage people to use the hyperion config option to achieve this.

**Comment by DrCard** [comment]
add this to the hyperion.config.json and now working 

	// BLACKBORDER CONFIG
	"blackborderdetector" : 
	{
		"enable" : true,
		"threshold" : 0.25,
		"unknownFrameCnt" : 600,
		"borderFrameCnt" : 50,
		"maxInconsistentCnt" : 10,
		"blurRemoveCnt" : 1,
		"mode" : "default"
	},


thank you so much
