### ISSUE TITLE
Add API controls

### ISSUE THREAD

**Issue by ValQuev** [abrenoch/hyperion-android-grabber#147]
Hi, first of all, thank you for this app.

Would it be possible to add an API that enable remote control of the led strip ?

Like put the led strip on or off, set a static color for the full led strip or set the full led strip on Hyperion mode ?

It would be great and it could permit an integration on some IoT hub

**Comment by abrenoch** [comment]
That sounds a bit out of the scope of this application to be honest. If you are trying to interface with hyperion then that should be done thru hyperion's API rather than anything thru this application.
