### ISSUE TITLE
IDEA: smartphone with local hyperion server + camera + ambilight 

### ISSUE THREAD

**Issue by hg42** [abrenoch/hyperion-android-grabber#157]
Hi,

I am new to ambilighting and currently waiting for my LED stripes from aliexpress (USB ambilight).

I have an LG TV which is also used as PC monitor.

While searching for solutions how to control these lights, I found your app.

Thinking about it, the best solutions seems to be like this:
* use an old smartphone
* use it's camera to grab the screen content, which also works for DRM etc.
* run a local hyperion server on the smartphone
* connect it via OTG to the ambilights
* run some full screen camera app
* run the hyperion grabber app to grab the screen

This looks very much like working out of the box.

But...

One problem to be solved would be the trapezoid shape of the screen inside the camera image.
There is a solution by manually changing the hyperion config file discussed here:
https://hyperion-project.org/threads/hyperion-source-from-cam-in-front-of-tv-prepare-input-region.2615/

I guess running a hyperion server on the smartphone could be possible, may be on Termux.
I'm not sure, if it could access the serial or other LED interface.

The perfect solution would be to
* integrate the hyperion server in the app
* add access to LED control interfaces if necessary
* add the camera as source
* do the trapezoid image processing while grabbing
* be able to touch on the four corners of the TV screen in the camera image to configure the trapezoid transfomation

Well, just some ideas...what do you think?

**Comment by abrenoch** [comment]
Interesting idea, but I think this strategy might be over complicating things a little bit. I **_really_** doubt you would be able to control the LEDs thru the android USB, so you would need to forward the signal to another hyperion instance on a raspberry pi to actually control the LEDs... And if you are at that point, it would make more sense to just use a camera hooked to the pi. The thread you linked to has some tips on adjusting the perspective on the hyperion side of things.

You could also look into using a splitter & capture device, which is supported by hyperion natively.

I think this is outside the scope of this app specifically so I'll close this out.
