### ISSUE TITLE
Is this project in active development? 

### ISSUE THREAD

**Issue by panec** [abrenoch/hyperion-android-grabber#159]
- Are there any plans for improvements, adding features, etc. 
- Will this app will go out of beta after releasing version 1.0
- Do you need any help with testing, or any other help that could help the development? 
- It there a way to help you by buying you a coffee - as I like this app and would like to see it supported over time

In general huge thank you from me & community for this grabber.

**Comment by tihoangyeudau** [comment]
Because drm is everywhere so i think it inactive

**Comment by abrenoch** [comment]
@panec I wouldn't consider this under _active_ development, but I wouldn't call it abandoned either. It started as a personal project and with the help of a few others we polished it enough for a release. I just haven't had the time to dedicate unfortunately. 
- As far as improvement go, there are a few ideas tossed out in the 'issues' area that appealed to me but that's about it. I would like to get flatbuffers added as that seems to be the protocol the latest hyperion.ng builds use. There may be ways to improve performance in general but I'm not sure how to go about identifying that TBH.
- There is one feature that hasn't made it into any releases yet (#150 ), but aside from that it is considered out of beta
- I'm always glad to accept any additional development efforts!
- I appreciate the offer, and would love to support it as long as I can... Unfortunately changes could be made to android, or even firmware to specific devices, that can break the app at any time. There really isn't anything that I know of that can do anything about this other that modifying your device, which I'm not sure works either.

@tihoangyeudau Sorry my man but there isn't anything I can do about the DRM

**Comment by tihoangyeudau** [comment]
@abrenoch i know but thank you for your try

**Comment by Hukuma1** [comment]
Just upgraded to latest Shield Experience 8.2 and seeing a flicker on my lights. Any one else able to confirm this? Trying to rule out other possible changes to setup to pinpoint new firmware as the cause.

**Comment by abrenoch** [comment]
@Hukuma1 I always hold my breath whenever I see one of those updates pushed... However my wife was watching TV with it last night and didn't mention anything like that to me. Are you using the 2017 or 2019 model?

**Comment by Hukuma1** [comment]
2019 Shield Tube. Can open new issue if needed.

https://imgur.com/D0XbOte

This is what I'm seeing. I turned off Smoothing option in Hyperion to really show it off. It's like it turns on/off frequently.

If I turn off your app and just test Hyperion NG static colors or rainbow effects it works without a hitch. So the issue is somewhere between Android TV app and Hyperion NG. Would love to figure it out because it was working flawlessly before haha D:

**Comment by Hukuma1** [comment]
Well I fixed it! Looks to have been in Hyperion NG under Platform Capture. Keeping the setting on auto (default) seems to cause the above effect. Switching it to Framebuffer fixes it immediately and works as expected. Sorry for the false alarm, but hey, now we also know it works on latest Shield Experience. Thanks for your hard work on this program. Hopefully you’ll be able to improve if as time allows in the future.

**Comment by abrenoch** [comment]
Really glad you got this worked out!

**Comment by Andirs55** [comment]
Can you please release a new version with [#150](https://github.com/abrenoch/hyperion-android-grabber/pull/150) included?
I dont know how to build myself.

Thanks in advance :)
