### ISSUE TITLE
What are the LED strip requirements?

### ISSUE THREAD

**Issue by alexwaibel** [abrenoch/hyperion-android-grabber#160]
What needs to be running on the attached USB device to run these LEDs? I have some LEDs attached to a knock-off Arduino Uno I purchased as a kit ([like this one](https://www.amazon.com/Adealink-Android-Computer-Backlight-Addressable/dp/B08CDT47KC/ref=sr_1_5?dchild=1&keywords=ambilight&qid=1598758023&sr=8-5)) and was wondering what sketch this app expects the Arduino to be running.

**Comment by abrenoch** [comment]
Hey @alexwaibel I think you may be misunderstanding how to set up the hardware for this. You will want something like a raspberry pi (I used a pi zero with the google power/ethernet adapter) to control the LEDs. This app is simply delivering the screen data to a hyperion device running on the same network. You will want to look into instructions on how to get hyperion up an running before using this app.
