### ISSUE TITLE
How to setup this

### ISSUE THREAD

**Issue by vbxlive** [abrenoch/hyperion-android-grabber#161]
I installed hyperion on raspberry pi and connected led to gpio 18,so how make settings in hyperion and hyperion grabber app to connect each other on my MI ANDROID TV help me.
Provide detailed setup details in wiki as well
Thank you

**Comment by abrenoch** [comment]
There are plenty of guides over at https://hyperion-project.org/ in regards to how to set up hyperion. This app simply uses the IP address of the device running hyperion, so any additional configurations of the hyperion server are outside the scope of this.

If you have any more specific problems feel free to respond.
