### ISSUE TITLE
Info Request

### ISSUE THREAD

**Issue by nytram-md** [abrenoch/hyperion-android-grabber#164]
Hi.

Is this for an actual android TV ?

Seen the DrZzs Hyperion on pi and capture loop card but also want to capture when I watch tv from my actual TV and saw this app when googling. 

I have sk6812w leds so just want to know what I need to connect to the TV.

Thanks

Martyn

**Comment by ikrowni** [comment]
This works with android tv and google tv. The way I have mine setup is WLED installed on a wemos d1 mini that talks to my hyperion server running as a home assistant add-on. You download this app onto the Android device and turn it on and it grabs the screen info and sends it to hyperion server which then sends the info to WLED.

**Comment by nytram-md** [comment]
Hi

I had same as you apart from a nodemcu for WLED and LEDs

I have had it only working on YouTube and the Home screen.

Once I go to the TV guide and pick anything it stops.

Same for HDMI.

Have you tried outside on TV and HDMI inputs ?

I have sony bravia TV

Thanks

Martyn

**Comment by ikrowni** [comment]
I think the problem you're running into is a DRM issue. It works great for me with syncler and smart youtube. But when I try netflix or amazon video it shuts down because those are both DRM protected.

**Comment by nytram-md** [comment]
Yes it seems you are hitting the same issue I had.

Which is a shame.

Fingers crossed for a DRM breakthrough

Martyn


Regards

Martyn

________________________________

**Comment by ikrowni** [comment]
Might have found a solution. I havent tried this yet but i will in just a bit

https://hyperion-project.org/threads/android-screen-grabber.2708/page-8#post-14842
