### ISSUE TITLE
Suggestion: Change default priority value

### ISSUE THREAD

**Issue by bpavlov** [abrenoch/hyperion-android-grabber#165]
Dear all,
Great product!
According Hyperio.NG documentation priority value for protobuffer should be between 100 and 199.
https://docs.hyperion-project.org/en/api/Guidelines.html#priority-guidelines

The initial value of the app is 50. So the app is not working with its default values. And the led lights do not turn pink.
Suggestion: Change initial value to 100.

Kind regards,
Boris

**Comment by cmsimike** [comment]
Thank you! This solved the issue I had.

**Comment by strech345** [comment]
Yes please change it.
Only because of this info i got it to run.

**Comment by Paulchen-Panther** [comment]
@abrenoch 
Can you please [change the priority](https://github.com/abrenoch/hyperion-android-grabber/blob/master/common/src/main/res/values/pref_values.xml) to 100-199, please?
Hyperion Classic was archived anyway. Many thanks.

Paulchen

**Comment by abrenoch** [comment]
> @abrenoch
> Can you please [change the priority](https://github.com/abrenoch/hyperion-android-grabber/blob/master/common/src/main/res/values/pref_values.xml) to [100-199](https://docs.hyperion-project.org/en/api/Guidelines.html#priority-guidelines), please?
> Hyperion Classic was archived anyway. Many thanks.
> 
> Paulchen

Sure, do you have a value in mind that would be preferable? Maybe like 150 if 100-199 if the range?

I admittedly haven't been keeping up to date with hyperion happenings, I should get the scoop. Glad to hear the new version is making progress!

**Comment by refthoom** [comment]
A value of 150 works fine for me. I couldn't get it to work before but this fixed it.

**Comment by Paulchen-Panther** [comment]
I have already adjusted the code. Maybe I'll do Issue #146 as well.
@abrenoch would then only have to create a new release on Google play.

**Comment by thundergreen** [comment]
Standard prio still at 50 .has not been merged yet ?

**Comment by Quotacious** [comment]
Yep, spent an hour changing many things trying to figure out why Play Store version (beta) didn't work, downloaded the APK from here, still didn't work. Eventually found a message board comment from 2 years ago saying the default 50 would not work, changed it to 150 and hurrah, finally!

**Comment by TheToto** [comment]
Same here, 3 years later. Works fine with 150, not with 50.
