### ISSUE TITLE
Question: send image without regard for LEDs?

### ISSUE THREAD

**Issue by cmsimike** [abrenoch/hyperion-android-grabber#166]
Hello!

Thank you for getting this up to the Android store!

I am currently evaluating using Android TV as a replacement for my current media player. My current media player runs Hyperion.NG with 2 LED sources using the X11 grabber. These LED sources are not really in sync with each other in terms of where the pixels line up, meaning the amount of horizontal and vertical LEDs on my TV are not matched up to how I sent up a secondary RGB strip (which has a different horizontal and vertical).
As this currently stands the lights work really well with my old media center and the strips are in sync where they need to be. Now that I'm trying out your Android app, I notice that the LEDs are no longer in sync, mostly due to the difference in LED locations of both strips.
I've previously seen other grabbers that can just send the image data (?? I might not be using the right terminology here) to my hyperion.ng instance and that instance then takes care of putting the pixels where they need to be based on the image sent. Is there anyway to just have your app send the image or pixel data to a hyperion.ng instance and not have it send where those pixels should exist?

Thanks!

**Comment by psychowood** [comment]
I second this, even if it is for a different use: I'd like to use Hyperion Grabber as an external grabber, replacing my current solution that uses an external webcam.

While it sort of works now if I open the camera app, manually position the phone, and zoom to frame the tv, it is not exactly "the" solution.

**Comment by abrenoch** [comment]
@cmsimike I think I understand what you are describing, but I have no idea why you would see different results using this app. I am simply sending image data to hyperion, what it decides to do with it from there may be outside the scope of this app. The LED counts in the settings simply help to dictate the resolution of the image being sent. Sending a full resolution image for example wouldn't really provide any benefits over a scaled down one if you have a low LED count, so it helps save resources.

Can you post a screenshot of what hyperion.ng is showing in the LED preview dialog?

**Comment by cmsimike** [comment]
Thanks for the reply! I ended up removing the shield from my entertainment setup (for unrelated reasons) so no longer have a way to reproduce this. Sorry!
