### ISSUE TITLE
Question: Does it work for Fire TV Stick 4K to stream directly to WLED?

### ISSUE THREAD

**Issue by strech345** [abrenoch/hyperion-android-grabber#167]
Hi,
I want to grab the colors from a fire TV Stick 4K (especially for Kodi) to stream it to a arduino ESP32 with WLED.

So i have the following questions:
- Will this app work on fire TV Stick? For example to grab content from Kodi?
- Can i connect this app directly with WLED (arduino ESP32), or do i need additional hyperion server?

for now ive this two things running, but i coudnt connect it to each other. So i understand that i need to run a separate hyperion server. But i dont know understand why i need this.

**Comment by ikrowni** [comment]
Not sure if it will fix your issue but try changing the message priority to something like 150.

I have this working with my new chromecast google tv device. LEDs lights hooked to wemos d1 mini with WLED installed and hyperion running as an add-on within my home assistant server

**Comment by enersis-pst** [comment]
hi @ikrowni 
yes thanks. i got it also running after change the prio. I ran it with a hyperion server on pi3.
For me it was the question if i really need a hyperion server, or if the android grabber can work directly with some arduino software like wled. I think for now its only possible by having a hyperion server running.

**Comment by strech345** [comment]
hi @ikrowni
yes thanks. i got it also running after change the prio. I ran it with a hyperion server on pi3.
For me it was the question if i really need a hyperion server, or if the android grabber can work directly with some arduino software like wled. I think for now its only possible by having a hyperion server running.

**Comment by ikrowni** [comment]
Yea I think you will have to have the hyperion server running in order to tell the sled instance what to do. The only other thing I can think is to use a capture card hooked to the rpi which will let you cut out the need for the hyperion screen grabber app. But that's just more costly hardware and requires more wires.

**Comment by MathiasAntunes** [comment]
Have you been able to connect the android grabber to Hyperion NG ?
I always have the same error : Unknow error.
The grabber works well on my smartphone with my hyperion NG server, but not on the stick (Priority is 150).
![IMG_20210219_193228](https://user-images.githubusercontent.com/23211270/108550372-c2263980-72ee-11eb-8d83-db26700e54ac.jpg)

Thx !

**Comment by strech345** [comment]
yes for me it works. also have same prio.
ip and port are correct? ive 19445.
maybe there is a app to ping hyperion server from fire tv stick. s check if its reachable

**Comment by MathiasAntunes** [comment]
Ok I finally got it working ! 
I don't really know what the issue was, but restarting the stick fixed it.
It might be linked to the ADB Hassio plugin that gets the stick status using Debug mode.

**Comment by thedevleon** [comment]
I had tried everything but a restart, which is all that was needed indeed...
