### ISSUE TITLE
Default priority 50 not working with Hyperion NG alpha 9

### ISSUE THREAD

**Issue by derzwen** [abrenoch/hyperion-android-grabber#168]
Tried to get this grabber working on my Shield 2019 Pro with latest Shield Software 8.2.1. Didn't manage until I looked through the logs from my Hyperion NG server (Alpha 9). Got lots of error messages like

"The priority 50 is not in the proto-connection range between 100 and 199."

So I changed the priority setting in the Android grabber settings from the default of 50 to 100 and tada, it worked. So maybe set this as a new default than in a fresh install?

**Comment by Telzuim** [comment]
I can confirm the problem. With an adjusted priority the connection works.

**Comment by tabbertmj** [comment]
I can also confirm the issue.  Once I changed the priority to 102 the connection started working.

**Comment by Paulchen-Panther** [comment]
The priority was changed in the source code. So it is only up to the release on the part of @abrenoch .
