### ISSUE TITLE
Grabber stops working when ccwgtv goes to sleep

### ISSUE THREAD

**Issue by ikrowni** [abrenoch/hyperion-android-grabber#171]
Is there anyway to send a command to start the grabber? After the device comes out of sleep I have to open the grabber app and click start to get it going.

**Comment by abrenoch** [comment]
There is an option to start the grabber again after the device wakes up, is that not working?

**Comment by ikrowni** [comment]
> There is an option to start the grabber again after the device wakes up, is that not working?

I have that option turned on but it doesn't seem to work. I was hoping that could be fixed or maybe there is a way to send an adb command to turn it on.

**Comment by abrenoch** [comment]
@ikrowni Well thats unfortunate... Not sure why it would be giving you trouble - unless maybe something changed that I'm not aware of.

For an adb command, checkout [this PR comment](https://github.com/abrenoch/hyperion-android-grabber/pull/150#issue-336051989).

**Comment by ikrowni** [comment]
> For an adb command, checkout [this PR comment](https://github.com/abrenoch/hyperion-android-grabber/pull/150#issue-336051989).

This looks like it will work perfect. I'll use home assistant to run the adb command when the status switches between playing and paused.

Thanks!

**Comment by abrenoch** [comment]
No problem, glad that helps!

I'm trying to get at least an update rolled out for this sooner than later... Far as I know that functionality works on my devices... Maybe I'll see if I can get my hands on one of those to test.

I'll close this - feel free to reopen if you are having trouble
