### ISSUE TITLE
Hyperion Android Grabber doesn't stream Netflix Content

### ISSUE THREAD

**Issue by msiemers** [abrenoch/hyperion-android-grabber#173]
I have the problem that the screen is streamed from the Sony to Hyperion, but nothing is transmitted when I start Netflix. Is this a mistake?

**Comment by krasatos** [comment]
As far as I know, netflix content is DRM protected, so it cannot work with hyperion.
According to [this](https://forum.xda-developers.com/t/remove-drm-on-rooted-4k-stick-hyperion-ng-with-netflix-co.4188005/), you will need to root your android device to bypass this limitation.
