### ISSUE TITLE
Add On/Off API Control

### ISSUE THREAD

**Issue by Burnsys2** [abrenoch/hyperion-android-grabber#176]
Basically an api endpoint to turn On/Off the grabber.

I have tasker in my androd TV and i configured it to publish mqtt messages reporting what is the current running aplication.

I would like for example to disable the grabber when using netflix (because it doesn't work with it) or when using youtube (video stuttering)

I found a similar issue that could be resolved with this functionality.

https://github.com/abrenoch/hyperion-android-grabber/issues/8

**Comment by abrenoch** [comment]
Hey @Burnsys2 , seems like you could probably use tasker to accomplish this by combining with the commands mentioned here: https://github.com/abrenoch/hyperion-android-grabber/pull/150#issue-516865142
