### ISSUE TITLE
Grabber not working at all

### ISSUE THREAD

**Issue by bcrowie** [abrenoch/hyperion-android-grabber#179]
I have Hyperion running in a docker image which is exposed via its own IP address. I have also tried running it on a raspberry pi 4. When I add the IP address and the protobuff port into the hyperion-grabber settings my WLED app shows that there is activity, a connection to that WLED instance, but when I activate the grabber the lights dont react at all. 

I have tried message priorities from 199 all the way to 50 decrementing by 10's. I dont understand where I am going wrong here. Can anyone help me out with this issue? I am running the hyperion grabber on a fire stick. I have also tried on two different android phones and am not seeing any response on the WLED connected light strips.

I have also attempted rebooting the fire stick and phones with no progress.

**Comment by abneits** [comment]
Same here after factory reset my shield few days ago,

All was ok before that and i do not have touch anything in my backoffice

**Comment by bcrowie** [comment]
Still having issues. I've tried everything I can think of including getting each device on the same subnet, reflashing WLED and reconfiguring it. The grabber just wont work.

**Comment by bcrowie** [comment]
No longer need assistance with this issue.
