### ISSUE TITLE
UDP loss and autostart no longer works

### ISSUE THREAD

**Issue by StEfDu6o** [abrenoch/hyperion-android-grabber#184]
Hello,
Since the Android 11 update on my ShieldTV Nivida, the application no longer starts on its own and if the image remains fixed for 5s the grabber stops (no more sending a signal to Hyperion) and resumes only if the picture moves. Not very pleasant to use...

**Comment by abrenoch** [comment]
duplicate of #180

Nothing in the app stops the grabber after any inactivity... I would need a video or something to get an idea of what you mean.

**Comment by Muegic** [comment]
Hi, I had the same issues with my Shield TV Pro after upgrading to Android 11.
(Grab on boot didn´t work and the LED´s went off after a few seconds with static picture).

Not sure what solved my problem in the end, but after fiddling arround, un- and reinstalling the Grabber app, updating software on WLED controller and Hyperion.ng, my problems are now mostly solved.
Static picture does not affect the backlighting anymore and grab on boot works most of the time for me (had to manually restart the grabber one, maybe two times whithin the last 30 days.

I'm currently running:
Hyperion Grabber 1.0
SHIELD Android TV SW Version 9.0.2(33.1.0.319)
WLED version 0.13.1
Hyperion.ng 2.0.12
