### ISSUE TITLE
Grabber on android tv reading from hdmi source

### ISSUE THREAD

**Issue by ycodryn** [abrenoch/hyperion-android-grabber#188]
Right now, grabber is installed on tv and is working just fine. I just bought a firestick to have more power, I had some lag watching movies on kodi/tv and android grabber. I also installed grabber on stick because is not working with the one from tv. Can this be done? To have the grabber installed only on tv but read the screen from stick ?

**Comment by durag5** [comment]
Yes I have grabber on my shield pro which is the same as a stick.

**Comment by ycodryn** [comment]
and the grabber is installed only on the tv os and not on the shield ?

**Comment by durag5** [comment]
The grabber is only installed on the shield, not the TV.

**Comment by ycodryn** [comment]
A ok, this way is working for me also.  I was thinking to make it work from tv os to hdmi input, without installing it on hdmi stick.
