### ISSUE TITLE
adb command to start 

### ISSUE THREAD

**Issue by Merkalov** [abrenoch/hyperion-android-grabber#190]
Hello. Is there an adb command to start the app to run from home assistant?

**Comment by Merkalov** [comment]
I found:
am start com.abrenoch.hyperiongrabber/com.abrenoch.hyperiongrabber.common.ToggleActivity

**Comment by LordBoos** [comment]
Please see my automation here: https://github.com/abrenoch/hyperion-android-grabber/issues/189#issuecomment-1297075174
