### ISSUE TITLE
Stop grabber if host in unavailable?

### ISSUE THREAD

**Issue by abrenoch** [abrenoch/hyperion-android-grabber#25]

**Comment by NisseDILLIGAF** [comment]
Maybe restart/try to reconnect if connection lost?
I have dodgy wifi and the grabber disconnects sometimes and then I have to manually disconnect and then reconnect..
I get to line 55 in _HyperionScreenService.java_
COULD NOT CONNECT TO HYPERION INSTANCE, (Broken pipe)
when connection lost.
My java/Android development skills isn't great, and I don't have much time, but I'll have a look in to it and try to find a solution...

Thanx for a great app, just what I was looking for :)

**Comment by NisseDILLIGAF** [comment]
This is working for me, #29 
Thanx @Paulchen-Panther
Only thing now is that if I set my Nvidia Android TV in standby, it wont reconnect...
But It's usually  on all the time anyway :)

**Comment by abrenoch** [comment]
resolved in 5cf3b6b847aa4a8edfce4842d87edaced6782c96
