### ISSUE TITLE
does it grab HW accelerated video?

### ISSUE THREAD

**Issue by pete111** [abrenoch/hyperion-android-grabber#27]
Hello, 
is your app able to capture HW accelerated video on android TV? 
If so, could you please send post here .apk file?

Many thanks

**Comment by abrenoch** [comment]
That seems to vary from device to device... I have a 2017 shield TV and it seems to work well for me for anything that isn't protected like amazon or netflix. You will just need to install it and see!

All apks are posted in the releases section:
https://github.com/abrenoch/hyperion-android-grabber/releases
