### ISSUE TITLE
Beta program not available worlwide

### ISSUE THREAD

**Issue by ninovanhooff** [abrenoch/hyperion-android-grabber#31]
I joined the Google Play Beta, but visiting this link from the Netherlands (and logged in with a google account registered in the Netherlands) gives me a 404:

https://play.google.com/store/apps/details?id=com.abrenoch.hyperiongrabber&hl=nl&ah=mFqaddBHxyVeSvhWrFsjCH4Bo90

Could you check that the beta is available worldwide?

**Comment by abrenoch** [comment]
It is available world wide (well, Solomon islands was disabled for some reason, but I changed that)! Did you join the google plus group first? It is unfortunately the only hands-off way for me to allow people to join the list of testers!

https://plus.google.com/communities/101526321905444484496

**Comment by ninovanhooff** [comment]
Yes, I did that yesterday. Currently, the same link works for me, so it seems Google needs some time to update permissions
