### ISSUE TITLE
Reload settings when settings are closed / updated

### ISSUE THREAD

**Issue by ninovanhooff** [abrenoch/hyperion-android-grabber#34]
It seems that the TV app does not notice that the host has been filled until the app is restarted

reproduce:
with a fresh install of the app:
- start the app
- open settings. the host is 0.0.0.0
- change host
- close settings
- click the on/off button

expected: hyperion is turned on
actual: toast message: Host must not be empty

After an app restart, the host is used, so the persistence is not the problem. Settings should be reloaded when settings are closed.

I'd be happy to fix this

**Comment by abrenoch** [comment]
Good catch - if you would like to submit a fix I would be glad to merge a PR!

**Comment by ninovanhooff** [comment]
Will do.

**Comment by abrenoch** [comment]
Hey @ninovanhooff  is this still an issue? In my testing of different branches and uninstalling/reinstalling the app I haven't ran into this problem!

**Comment by ninovanhooff** [comment]
Exactly what I just found out! closing
