### ISSUE TITLE
Stops randomly

### ISSUE THREAD

**Issue by ziggy73701** [abrenoch/hyperion-android-grabber#35]
Not sure the best way to describe this. Using the grabber on a Shield. Works perfect for a while then the lights will freeze. Going to grabber, turn off and on and all good. No consistency in how long it works, but works no longer than 35 mins.
Any logs or anything I can look at?
Using Alpha 2

**Comment by ninovanhooff** [comment]
I've also experienced this

**Comment by NisseDILLIGAF** [comment]
See my comment here...
https://github.com/abrenoch/hyperion-android-grabber/issues/30#issuecomment-390730832

I don't have freezes any longer...

**Comment by abrenoch** [comment]
@NisseDILLIGAF  I'll give your solution a try for a while today and see if it helps! Weird that the scoping of that variable would fix it, but I have certainly seen weirder... Maybe that would be a GC thing then!

**Comment by abrenoch** [comment]
That fix seems to have done the trick! There is still the problem with that version of the grabber not restarting when waking from sleep, but that is a different problem.

Implemented in 66667a2130e872192db548ad94f80d8ba7366426
