### ISSUE TITLE
Scan for hyperion server on the local network

### ISSUE THREAD

**Issue by ninovanhooff** [abrenoch/hyperion-android-grabber#38]
Punching in ip addresses and port numbers sucks, especially on a TV. Let's try to find a running hyperion server if the settings haven't been filled yet. Currently working on this

✓ investigate technical feasibility
✓ Implement Scanner
▶ TV UI
◌ Mobile UI

**Comment by abrenoch** [comment]
Fantastic idea - I had noticed inputting that info on android tv blew as well. I had hoped when I switched over to the TV theme that would improve, but it didn't. Why didn't google make that better haha.

That is a damn fine way to get around the problem though! Looking forward to seeing it!

**Comment by Paulchen-Panther** [comment]
I implemented the network search last weekend. I hope I can put the PR this week still pure.

**Comment by ninovanhooff** [comment]
Such a shame we are doing double work @paulchen-Panter. @abrenoch: can we invite him to the project board?

**Comment by abrenoch** [comment]
Got @Paulchen-Panther added to the project! (I swear I posted that earlier, but I'm not seeing it here now... odd)

@Paulchen-Panther if you want to join the slack channel as well just shoot me an email at nlclothing[@]gmail and I will add you to the list!

**Comment by Paulchen-Panther** [comment]
@ninovanhooff 
I've looked at your branch hyperion_scanner. You search the network for IP addresses, if I see it correctly. I took another way.
The classic Hyperion and the successor Hyperion.NG provide their IP addresses and the Proto port via Zeroconf. Thus, it is not really necessary to search the network for IP addresses.
Here is the source line of the classic Hyperion: [LINK](https://github.com/hyperion-project/hyperion/blob/master/src/hyperiond/hyperiond.cpp#L250)
And here from Hyperion.NG: [LINK](https://github.com/hyperion-project/hyperion.ng/blob/master/src/hyperiond/hyperiond.cpp#L352)

I also uploaded my scanner class here: [LINK](https://gist.github.com/Paulchen-Panther/95c191bfdae649cb058ebc55c7bf2e9a)
Maybe it will help you.

@abrenoch 
Thanks for the project invitation. :+1:

**Comment by ninovanhooff** [comment]
@Paulchen-Panther I was not aware that Hyperion supports zeroconf. Your code seems clean and while I have not tested it, I'm pretty sure your approach is the one to go for, since it also supports hyperion servers with non-default ports. Great job!

It would be great if we could combine our work. Assuming that you have not created a user interface yet, this is what I propose:

- I move my code to a branch in @abrenoch 's   (this) repository. We both have write access here.
- you create a new branch off of my branch where you replace my scanner by your own.
I suppose you could just start it in `doInBackground` and let it run for 3 seconds. Call `publishProgress` a few times per second (eg. after 2 seconds the progress is 66%) and return the first hostName as soon as you find it.
- I will continue my work on the TV interface
- Maybe you'd like to work on a phone interface
- Letting the user select from a list of found servers is an extra feature which we could leave for another PR. Either of us could pick it up when we have extra time to spend.

Do you agree with this approach?

**Comment by Paulchen-Panther** [comment]
Sounds very good. Unfortunately, my time is limited. Thus, I will do more at the weekend as in the week. Let's get it started. :-)

**Comment by ninovanhooff** [comment]
There you go: https://github.com/abrenoch/hyperion-android-grabber/tree/feature/hyperion_scanner
please create your branch off of that

**Comment by ninovanhooff** [comment]
Hey @Paulchen-Panther , I have a new idea for the scanning time calculation:

- By default, the scanning will be stopped 3 seconds after the starting time, 
- When the first result comes in, the end time will be set 0.5 seconds from that moment, or 3 seconds from the start whichever comes first

So when the first result comes in after 0.7 seconds, the total scanning time will be 1.2

When the first result comes in at t=2.7, the total scanning time becomes remain 3.0, since we only use the first result anyways.

**Comment by Paulchen-Panther** [comment]
@ninovanhooff

scanning time calculation plays no role in zeroconf service. Basically, you start the resolve service with the Activity and stop the service after selecting a server. This has the advantage, registered servers will be deleted from the found list (callback to the activity) immediately as soon as they are no longer available in the network. The only problem I still have is moving your activity so that it displays the callback list in the form of Server buttons to select.

**Comment by ninovanhooff** [comment]
Ah, I thought you would just keep scanning until you found the first one like suggested above. Anyways, do you need help with that?

**Comment by Paulchen-Panther** [comment]
choose the first server will only work if there is only one instance in the network. in two instances it is lucky to hit the right one.

**Comment by Paulchen-Panther** [comment]
@ninovanhooff 

I have created a new branch (feature/hyperion_tv_wizard) in this repository. There you can now see the functionality of Network Service Discover.

**Comment by ninovanhooff** [comment]
@Paulchen-Panther 

What version of the hyperion server is needed for zeroconf? I'm using it on a raspberry pi, and I don't get any results. (looking at the code, I understand that when a service is found it should be added above the dropdown labeled "Manually"). 
As a user, I was a bit confused about where to start a scan, not knowing that the scan was already running in the background. Maybe that could be improved.

I agree that GuidedSteps could be a good approach for the manual setup. In fact, I have implemented the same thing. 
Could you maybe join the Slack channel, so we can easily keep each other up to date on each others progress?

**Comment by Paulchen-Panther** [comment]
I just see the zeroconf in the classic hyperion is off.
https://github.com/hyperion-project/hyperion/blob/master/CMakeLists.txt#L20
But it would have to be switched on with the compilation option -DENABLE_ZEROCONF = ON.

In the successor NG it is always activated.

**Comment by Paulchen-Panther** [comment]
> @Paulchen-Panther if you want to join the slack channel as well just shoot me an email at nlclothing[@]gmail and I will add you to the list!

you have mail

**Comment by ninovanhooff** [comment]
The conclusion is that @Paulchen has the better approach, but it will only work with hyperion NG. My port scanner has been included instead. It is only accessible on first app start at the moment.
