### ISSUE TITLE
Grabber should fail to start if the provided host in unreachable?

### ISSUE THREAD

**Issue by abrenoch** [abrenoch/hyperion-android-grabber#41]
It seems like when turning on the grabber, and the host is unreachable, the grabber should be turned back off and convey to the user that the provided host is unreachable.

Any thoughts on this from anyone? Seems like the right move to me, though we may need to look at how this interacts with the reconnect behavior (maybe not).

**Comment by ninovanhooff** [comment]
In my opinion, re-connecting should only be done when there was a connection in the first place. When the initial connection attempt fails, the scanner should be turned off and a descriptive Toast should be shown

**Comment by abrenoch** [comment]
I agree about the reconnect - seems like we can probably achieve that by simply storing a boolean in the `HyperionThread` class that gets to `true` once it successfully connects once. Then just use that boolean along with the `RECONNECT` boolean while evaluating if for the need to reconnect. Seems like a couple small edits would do the trick.

I also have a few thoughts on the open PR for this, but I'll get at you on slack for that!
