### ISSUE TITLE
Clear lights when shutting down.

### ISSUE THREAD

**Issue by abrenoch** [abrenoch/hyperion-android-grabber#47]
It appears when restarting or shutting down the device kills the service without the lights being cleared.

**Comment by ninovanhooff** [comment]
In addition we could do this on a screen off event. I think it happened to me that the lights stay on when the screen turns off without fading to black. Yet another safeguard could be to set the duration of the image / color requests to 2*(reconnect timeout)

**Comment by abrenoch** [comment]
Leveraging the duration of the image sounds like a very interesting way to try and approach this, very elegant too IMO!

I'll see if we can get the behavior we want out of just that change before tweaking the broadcast receiver!

**Comment by abrenoch** [comment]
Well I had forgotten the ImageReader only sends frames when the screen actually updates - so unfortunately the frame duration isn't going to be a great way to handle this since it would turn the lights off after x seconds of an unchanged screen.

Broadcast receiver it is then!

**Comment by Paulchen-Panther** [comment]
#68
