### ISSUE TITLE
Optionally start grabber with OS

### ISSUE THREAD

**Issue by abrenoch** [abrenoch/hyperion-android-grabber#6]

**Comment by abrenoch** [comment]
Looks simple enough to implement:

https://stackoverflow.com/a/6392009/2118233

**Comment by abrenoch** [comment]
Turns out to be a bit of a pain... It seems like `startActivityForResult` needs to be called to get the resulting intent with the correct permissions granted (far as I can tell). Calling that from outside an activity looks like a hassle. I could make it work by focusing the activity for a split second then ending it, but I would prefer to find a better solution than that.

**Comment by Paulchen-Panther** [comment]
this may be helpful:
[stackoverflow](https://stackoverflow.com/a/33892817)
[github](https://github.com/kundankale/Task2/tree/master/app/src/main/java/in/omerjerk/screenshotter)
