### ISSUE TITLE
Bugs and improvements

### ISSUE THREAD

**Issue by Paulchen-Panther** [abrenoch/hyperion-android-grabber#71]
### Platform:
- **_Mobile_**:
- - (**BUG**) Toast "message_service_started" not in the foreground in landscape mode
- - (**BUG**) Warning toast (error_empty_host) appears as often as the application was in the background
- - (**IMPROVEMENT**) Open Hyperion Grabber after clicking on Notification (Example link: https://stackoverflow.com/questions/13716723/open-application-after-clicking-on-notification)

- **_General_**:
- - (**IMPROVEMENT**) HyperionNotification.java move Hardcoded Strings (NOTIFICATION_CHANNEL_LABEL, NOTIFICATION_TITLE and NOTIFICATION_DESCRIPTION) to XML.

**Comment by abrenoch** [comment]
Took care of everything but that bug with `error_empty_host`. Could you elaborate on that a little please? I'm not sure I know exactly what you mean!

**Comment by abrenoch** [comment]
Hmm, maybe a screen recording would help. I think I am following the steps correctly, but am still only seeing one toast!

**Comment by Paulchen-Panther** [comment]
I uploaded a screen record and the logcat.
My Mobile OS is MIUI 9.5 from Xiaomi. The phone is a Redmi Note 4X.
The steps I did:
1. New installation
2. Hyperion Grabber open
3. pressed on start
4. Error Toast "error_empty_host" appears once
5. Press the back button
6. open hyperion grabber again
7. pressed again on start
8. -> Now the error toast "error_empty_host" appears twice
9. pushed back again
10. Hyperion Grabber opened again
11. pressed again start
12. error toast appears three times
13. And so on ...

Logcat: https://pastebin.com/vdKHqYDY
Screen record: https://streamable.com/ob1jn

**Comment by abrenoch** [comment]
Thanks for the video, that certainly helps me understand!

I'll try to reproduce this on my device later!

**Comment by Paulchen-Panther** [comment]
thank you

**Comment by abrenoch** [comment]
Could you please try this again in the `development` branch please? I tried to re-create this and was unable, but I was running some newer code.

**Comment by abrenoch** [comment]
I haven't been able to reproduce this behavior on the current `development` - am going to close this for now.

Please re-open this if you find the issue still persists!
