### ISSUE TITLE
Leds stay lit when turning off the grabber (low led counts only)

### ISSUE THREAD

**Issue by ninovanhooff** [abrenoch/hyperion-android-grabber#80]
Observed on Shiekd TV

*reproduce*

- setup as usual, but choose a value of `2` for horizontal and vertical led count
- turn grabber on & off again.
-> The leds stay on

Does not happen always but quite frequently

**Comment by abrenoch** [comment]
Can confirm, I also see this happen, but not 100% of the time.

**Comment by abrenoch** [comment]
I believe this got resolved in the average color merge... I'll close this out for the time being.
